### ISSUE TITLE
Změna velikosti okna, do kterého píšeme

### ISSUE THREAD

**Issue by khavlic** [amio-io/amio#1]
Dobrý den, prosím, zda by šlo zvětšit (i ručně zvětšit) okno, do kterého píšeme klientovi informace. Velikost na dva řádky je velmi malá. Děkuji. Karolína Havlíčková (Generali)

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #2](https://github.com/amio-io/amio-issues-generali/issues/2) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #5](https://github.com/amio-io/amio-issues-generali/issues/5) via [**ZenHub**](https://www.zenhub.com/)
