### ISSUE TITLE
dvakrát zobrazený text

### ISSUE THREAD

**Issue by zstehl** [amio-io/amio#11]
Opět se nám v některých případech objevuje dvakrát text psaný operátorem. Stává se to jen v IE, v chromu ne. Zkoušela jsem nasimulovat, kdy se to objevuje, ale tentokrát na to enter nemá vliv. Jeden text je zobrazen jako od TGL a druhý ode mě ZST.
![image](https://user-images.githubusercontent.com/31691144/31069336-5950b59a-a75c-11e7-9d9e-a44d2f61f629.png)

**Comment by zatziky** [comment]
@zstehl Jdeme se na to hned podívat, ale zatím nemáme moc indicií...
