### ISSUE TITLE
[Mobile] Login page is missing login :-)

### ISSUE THREAD

**Issue by JanMikes** [amio-io/amio#13]
After refresh the login stuff appears in 😉 

![img_0974](https://user-images.githubusercontent.com/3995003/41398269-13ab7204-6fb7-11e8-9fdc-bc0ce7fd83fc.PNG)

**Comment by kuceram** [comment]
Hi Jan, this issue was already reported. We're working on new login page with our provider. It's going to be live in two weeks approximately.

Thanks for your report anyway!

**Comment by zatziky** [comment]
Čau Honzo, @JanMikes

check if the issue persists. If yes, feel free to open it again. ;) Thank you for reporting it!

Honza
