### ISSUE TITLE
[Mobile] Google signup does not let me choose account

### ISSUE THREAD

**Issue by JanMikes** [amio-io/amio#14]
Hey, i have like 20 google acocunts :-) when i click the "sign up with the google" button, it instantly picks up the first account and does not let me choose which one i would like to use.

I ended up creating account regularly with e-mail address, because of that.

**Comment by kuceram** [comment]
Hi Jan, we will try to investigate this issue with our new login implemented within two weeks.

**Comment by zatziky** [comment]
I had a call with Jan Mikes and he verified it's working now.
