### ISSUE TITLE
[Mobile] Responsivity is not the best in admin

### ISSUE THREAD

**Issue by JanMikes** [amio-io/amio#15]
There are scrollbars allowing me to end up with screen like this 😉 

![img_0976](https://user-images.githubusercontent.com/3995003/41398427-9870fd74-6fb7-11e8-8d1a-bbd34b32df18.PNG)

**Comment by kuceram** [comment]
Hi Jan, this issue was already reported. We're working on new login page with our provider. It's going to be live in two weeks approximately.

Thanks for your report anyway!

**Comment by zatziky** [comment]
Čau Honzo, @JanMikes

check if the issue persists. If yes, feel free to open it again. ;) Thank you for reporting it!

Honza
