### ISSUE TITLE
smajlík a příloha se otevírají ve stejném okně

### ISSUE THREAD

**Issue by khavlic** [amio-io/amio#2]
Dobrý den, smajlík a příloha typu např. jpg se otevírají ve stejném okně jako je Amio, takže musíme zadat zpět, abychom se dostali zpátky na konverzaci. Prosíme, zda by se přílohy mohly otevírat v jiném (dalším okně). Děkujeme Karolína Havlíčková (Generali)

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #3](https://github.com/amio-io/amio-issues-generali/issues/3) via [**ZenHub**](https://www.zenhub.com/)
