### ISSUE TITLE
Being logged, navigation to app.amio.io/login redirects to /not-found

### ISSUE THREAD

**Issue by zatziky** [amio-io/amio#20]
**Summary:**
[Dayswaps](https://dayswaps.com) reported that while being logged, when they navigate to https://app.amio.io/login they are redirected to https://app.amio.io/not-found

**Expected results:**
Redirect to https://app.amio.io

**Actual results:**
Redirect to https://app.amio.io/not-found

**Comment by kuceram** [comment]
This issue was fixed.
