### ISSUE TITLE
FB Messenger - Add support for persistent menu in different locales

### ISSUE THREAD

**Issue by burningtree** [amio-io/amio#22]
In original Messenger API is possible to create different menus for different locales, which is really needed for multi-language environments. Can you please add this functionality to `/v1/channels/channel_id/settings` API endpoints?

Source:
https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/persistent-menu/

**Comment by zatziky** [comment]
Hey @burningtree,

we're aware that FB has this support. You the first to ask this feature but I guess that more people will demand it too. **We will start analyzing the localized menu on Monday.** I'll keep you informed.
