### ISSUE TITLE
Facebook BUG: cannot add new FB channel

### ISSUE THREAD

**Issue by zatziky** [amio-io/amio#24]
From today, Facebook has a bug in their API. For this reason it's not possible to add new Facebook channel to Amio. This is the FB bug - https://developers.facebook.com/bugs/614998752288654/

We're trying to find a hot fix now.

**Comment by kuceram** [comment]
Hot fix was released. Waiting for Facebook for complete fix.

**Comment by kuceram** [comment]
We made a fix of this.
