### ISSUE TITLE
Allowed field in error response

### ISSUE THREAD

**Issue by slezakjiri** [amio-io/amio#26]
I have called `POST channels/{{CHANNEL_ID}}/settings` with key `xxx`. The response error is:
```
{
    "timestamp": "2019-04-18T07:20:19.116Z",
    "status": {
        "code": 422,
        "message": "Unprocessable Entity"
    },
    "errors": [
        {
            "message": "Property 'xxx' is not supported.",
            "field": "xxx"
        }
    ]
}
```

The error is not very helpful. What are the allowed fields?

**Comment by zatziky** [comment]
Hello Jiri,

we will address this issue within 2 weeks. I'll let you know as soon as it's solved. Thanks for reporting! 👌

**Comment by zatziky** [comment]
Hey Jiri, @slezakjiri 

we have updated the api error response and now the errors look like this:

```json
       {
            "message": "Property 'user_input_enabled' is not supported. Allowed fields are 'user_inputs', 'menu', 'get_started_button'",
            "field": "user_input_enabled"
        }
```
