### ISSUE TITLE
Default recipient country code

### ISSUE THREAD

**Issue by ghost** [amio-io/amio#27]
Hi there,
we just sent two test sms and one of them did not work as expected.
The first number was with country code +420 and the second one was without country code. Somehow messagebird used country code +32 for that second one and i do not know it there is a problem in your library or in messagebird.
We found some setting in messagebird here: https://www.dropbox.com/s/klmgy76q60l3nbd/Screenshot%202019-05-16%2015.19.27.png?dl=0 but it is already set to Czech republic not to Netherlands. Thanks a lot

**Comment by zatziky** [comment]
@schefpet thank you for the report. 

We are having a look at it. 🔍 I let you know soon.

**Comment by zatziky** [comment]
@schefpet 
### 
We have verified that we don't send any default prefix to MessageBird. We've asked MessageBird on Slack and we're waiting for their reply.

### In-house default prefix
In the meantime, you can workaround by adding +420 to phone numbers that are missing it. If you ever plan to hit other markets than the Czech Republic, it may be the preferred solution because in every country you would put a specific prefix.

**Comment by ghost** [comment]
Sure we count with that in a future. But we did not expected we have to solve that immediately.

**Comment by zatziky** [comment]
@schefpet Unfortunately, in MessageBird the "**DEFAULT RECIPIENT COUNTRY**" does not apply to API calls. I'll label this issue as a **feature request** if you agree. First, we'll have to find out whether it's a real benefit to add a **default country prefix**.

See MessageBird support response:

![image](https://user-images.githubusercontent.com/2794365/57910833-da059980-788e-11e9-9f22-20ccc269cab1.png)

**Comment by zatziky** [comment]
@schefpet Petr, after discussion with you, I've updated our [documentation](https://docs.amio.io/reference#mobile-messages-text). Now, we clearly say that **prefix must be included**:

![image](https://user-images.githubusercontent.com/2794365/57924528-ff55d000-78ad-11e9-899e-6146b4ad154e.png)

Hopefully, it will save time others using mobile API. ⏳

Thanks for your feedback! 👍🏼
