### ISSUE TITLE
Uzavření konverzace

### ISSUE THREAD

**Issue by khavlic** [amio-io/amio#3]
Dobrý den, když klient odepíše, např. se rozloučí, už mu nebudeme psát, tak konverzaci uvidíme jako neodpovězenou (tučně). Potřebujeme nějak tyto konverzace označit nebo ukončit, aniž bychom klientovi něco odepisovali. Potřebujeme tyto konverzace nějak "odtučnit".  Děkuji Karolína Havlíčková (Generali).

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #4](https://github.com/amio-io/amio-issues-generali/issues/4) via [**ZenHub**](https://www.zenhub.com/)
