### ISSUE TITLE
Too many queues on RabbitMQ

### ISSUE THREAD

**Issue by javiertrancoso** [amio-io/amio#31]
### Context
Right now we are getting too many queues in very short times, due to our plan on CouldAMQP we cannot have more than 1000 queues. Every time that it overpasses the limit we get the next mail:

"You currently have 1188 queues in your CloudAMQP account Amio Dev/cbspkgar. Shared plans are not allowed to have more than 1000 queues. Please make sure that you delete unused queues, eg. with the auto_delete flag, a queue-ttl or manually cleaning them up. If you use Python Celery, make sure that you consume the results or disable the result backend (set CELERY_RESULT_BACKEND = None)."

![image.png](https://images.zenhubusercontent.com/5d75f98deb71d10001e817fa/6cf2a049-a35d-4325-971d-b18d96d6f73a)
(The number of queues highly increases when testing)

### Task
- [ ] Find the root of the issue
- [ ] Create a task for the issue

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-adapter-x #19](https://github.com/amio-io/amio-adapter-x/issues/19) via [**ZenHub**](https://www.zenhub.com/)
