### ISSUE TITLE
Našeptávání vět

### ISSUE THREAD

**Issue by khavlic** [amio-io/amio#4]
Dobrý den, prosíme, zda by šlo nastavit používání zkratek. Abychom pod nějakou zkratkou např. tečkou, měli možnost si uložit často používané věty. Děkuji Karolína Havlíčková (Generali)

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #6](https://github.com/amio-io/amio-issues-generali/issues/6) via [**ZenHub**](https://www.zenhub.com/)
