### ISSUE TITLE
chyba při odeslání víceřádkového textu

### ISSUE THREAD

**Issue by zstehl** [amio-io/amio#5]
Při odeslání víceřádkového textu nedošlo k odeslání, tři řádky ještě ano, čtyři už klient nedostal. Objevila se chybová hláška
![image](https://user-images.githubusercontent.com/31691144/30105899-343c5ca8-92fa-11e7-8730-4344d15e1b97.png)

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #7](https://github.com/amio-io/amio-issues-generali/issues/7) via [**ZenHub**](https://www.zenhub.com/)
