### ISSUE TITLE
dvakrát zobrazená zpráva

### ISSUE THREAD

**Issue by zstehl** [amio-io/amio#7]
v některých případech se mi dvakrát zobrazuje text, který jsem odeslala. Klientovi se zobrazil jen jednou. Vyvolat se mi to podařilo, když jsem dala enter, backspace a pak klikla na send
![image](https://user-images.githubusercontent.com/31691144/30106851-201bf01e-92fd-11e7-86b3-a0506cd6c0f0.png)

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #9](https://github.com/amio-io/amio-issues-generali/issues/9) via [**ZenHub**](https://www.zenhub.com/)
