### ISSUE TITLE
nový text klienta neskáče nahoru

### ISSUE THREAD

**Issue by zstehl** [amio-io/amio#8]
Chat s novým textem klienta neskáče nahoru, konverzace se přesune nahoru až poté, co tam text napíše operátor.

**Comment by zatziky** [comment]
Dobrý den, bugy pořešíme ve Vašem repozitáři. :-) Překopíruji ji je tam.

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #19](https://github.com/amio-io/amio-issues-generali/issues/19) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zatziky** [comment]
Bug je odstraněn. Můžete v pondělí otestovat.
