### ISSUE TITLE
označení ukončené konverzace

### ISSUE THREAD

**Issue by zstehl** [amio-io/amio#9]
Novou funkci na označení komunikace jako přečtené zde máme, ale po kliknutí na označit jako zodpovězená se nic nestane a stále je tučně. Odzkoušeno přes tři tečky i napravo u klienta.  Tučné to přestalo být až po té, co jsem si nechala zobrazit jen nepřečtené. Opačně to bylo stejné, na tučnou se změnila až po zobrazení jen nepřečtených.

**Comment by zstehl** [comment]
po odhlášení a přihlášení již funguje

**Comment by zatziky** [comment]
Dobrý den, bugy pořešíme ve Vašem repozitáři. :-) Překopíruji ji je tam.

**Comment by zatziky** [comment]
Issue moved to [amio-io/amio-issues-generali #18](https://github.com/amio-io/amio-issues-generali/issues/18) via [**ZenHub**](https://www.zenhub.com/)
